### PR TITLE
Cleaned up unnecesary code

### PR DESCRIPTION
**Pull request by LinsaFTW**
Return on server connect if cancelled.
Register intent only when is needed (No need to register it so early)

### CODE REVIEW

**Comment by xknat** [comment]
This will be reviewed after i commit my changes from local

**Comment by LinsaFTW** [comment]
Just saying this has been tested on a 300 player server and its working perfectly :)

**Comment by xknat** [comment]
@LinsaFTW Your on our discord server? can you mention me there?

**Comment by aljaxus** [comment]
cc: @xknat

**Comment by xknat** [comment]
@LinsaFTW sorry for the wait but its now merged <3

**Pull request merged**
