### PR TITLE
Add Russian locale file

### PR DESCRIPTION
**Pull request by NyanGuyMF**

### CODE REVIEW

**Comment by Angel-0** [comment]
Hello, thanks for you pr, it's very appreciated 😄 

However, it won't be merged until we'll have an use for it ^^

**Comment by xknat** [comment]
@MrZillaGold is this one better? https://pastebin.com/raw/Lm7fBSZY
kindly let us know, feel free to contact us on discord. (https://discord.me/skinsrestorer)

**Comment by MrZillaGold** [comment]
I made a change to the translation file: https://pastebin.com/raw/ANd5UZTD

**Comment by xknat** [comment]
@NyanGuyMF we decided to move over to crowdin, i did implement your translation but there are 253 new words that needed to be translated.
You can apply to translate russian on our project page here: [https://crowdin.com/project/SkinsRestorer](https://crowdin.com/project/SkinsRestorer )
THanks in advance!
~knat

**Pull request closed without merging**
