### PR TITLE
Set minimum to 5

### PR DESCRIPTION
**Pull request by xknat**

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
Why is this needed? We already have defaults.

**Comment by xknat** [comment]
> Why is this needed? We already have defaults.

to prevent people setting it to 0

**Comment by xknat** [comment]
Also, i am considering increasing the default values.
Eclipse can't keep up it seems...

**Comment by AlexProgrammerDE** [comment]
Eclipse can keep up atm. It's because we didn't perfectly optimize it on our end and that caused trouble.
The few people who actually set it to 0 likely have a valid reason for it/we might allow using custom apis in the future, so caching should be disableable.

**Comment by AlexProgrammerDE** [comment]
I don't think this is our biggest bottleneck at the moment, eclipse traffic is a non-issue now. 
I think also barely any servers have it set to that and I think some have a good reason for it.

**Pull request closed without merging**
