### PR TITLE
If use the geyser plug-in, the bug is resolved that does not synchronize skin of Bedrock client's character.

### PR DESCRIPTION
**Pull request by rosiecube**
…ronize skin of Bedrock client's character.

### CODE REVIEW

**Comment by xknat** [comment]
If this is a floodgate / geyser only issue. i dont think we should do this on all servers...
some have other plugins...

**Comment by Logics4** [comment]
If this fixes the issue for Bedrock clients while not introducing new bugs for the platforms we officially support, i don't see why we should not accept this @xknat

**Comment by Camotoy** [comment]
This is something we should fix on our end first, though. @rosiecube can you provide replication steps?

**Comment by rosiecube** [comment]
I will register as a bug issue of geyser.

**Pull request closed without merging**
