### PR TITLE
Add support for all bukkit versions

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**

### CODE REVIEW

**Review by xknat — CHANGES_REQUESTED** [review]
Not all servers use multiverse, some may use multiworld,
If they do not use multiverse, we would need to inform them that it will only work with multiverse.

**Comment by AlexProgrammerDE** [comment]
What does that have to do with older bukkit versions?

**Comment by xknat** [comment]
ah multiver =/= multiverse i see

**Review by xknat — APPROVED** [review]
LGTM but this may need some testing and i also think that if we support 1.7 they expect us to support modded etc

**Pull request merged**
