### PR TITLE
Rename locale_zh_hk.json to locale_zh_cn.json

### PR DESCRIPTION
**Pull request by DongShaoNB**
It should be named locale_zh_cn.json

### CODE REVIEW

**Comment by xknat** [comment]
We use https://minecraft.fandom.com/wiki/Language and not ISO 639-3

**Comment by DongShaoNB** [comment]
> We use https://minecraft.fandom.com/wiki/Language and not ISO 639-3

yes, Chinese Simplified -> zh_cn
image

**Comment by xknat** [comment]
Ah it was put on hk
Do you know if the HK language is different from the normal cn language?

**Comment by xknat** [comment]
Changed, crowd in will commit the pr

**Comment by DongShaoNB** [comment]
> > We use https://minecraft.fandom.com/wiki/Language and not ISO 639-3
> 
> yes, Chinese Simplified -> zh_cn image

Both hk and tw are Chinese Traditional , 99% of them are the same, but Chinese Simplified(normal cn language) different from them. The file that i changed is Chinese Simplified

**Comment by DongShaoNB** [comment]
> Ah it was put on hk Do you know if the HK language is different from the normal cn language?

Both hk and tw are Chinese Traditional , 99% of them are the same, but Chinese Simplified(normal cn language) different from them. The file that i changed is Chinese Simplified

**Pull request closed without merging**
