### PR TITLE
Fix illegal username chars for /skin set player

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Not tested, but I think it should. Needs testing.

### CODE REVIEW

**Comment by xknat** [comment]
Will test when home

**Review by xknat — COMMENTED** [review]
issue is still there, i am using /skin set user xknat
image

/skin update has same issue
/sr drop player *MRKnat does work

**Comment by xknat** [comment]
image

**Comment by MrRazamataz** [comment]
I installed the latest version from Spigot and this is still an issue

**Comment by xknat** [comment]
> I installed the latest version from Spigot and this is still an issue

GitHub follows Dev branch.
GitHub => coding issues
Discord => support

**Pull request merged**
