### PR TITLE
Bumps

### PR DESCRIPTION
**Pull request by JT122406**

### CODE REVIEW

**Review by AlexProgrammerDE — CHANGES_REQUESTED** [review]
I don't think our CI needs to run on java 18. We only have 17 to compile our java mappings.
The plugin compiles to java 1.8 anyway.

**Comment by JT122406** [comment]
> I don't think our CI needs to run on java 18. We only have 17 to compile our java mappings.
> The plugin compiles to java 1.8 anyway.

Yeah it’s just to speed up the workflow since it’s a little faster

**Review by xknat — CHANGES_REQUESTED** [review]
17 is LTS while 18 is not.

**Comment by JT122406** [comment]
Java 17.0.3 is used in workflow now

**Review by xknat — APPROVED** [review]
i do approve of using 17.0.3

**Review by AlexProgrammerDE — CHANGES_REQUESTED** [review]
I do not agree with forcing a specific java version for build. When setting major version to just 17, it will try to use the local java version on the runner or else download the latest one automatically. There is no difference for us between using different minor versions as they compile to the same jvm code. 
I would propose we set it back to major version 17, without pinning down the release version and then add the fetch latest option, which may slow down build in some cases. https://github.com/actions/setup-java#check-latest

**Comment by xknat** [comment]
@JT122406 thanks for the effort, much appreciated ❤️

**Pull request closed without merging**
