### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cmod31**
I fixed the dev build button it gave me a 404

### CODE REVIEW

**Comment by xknat** [comment]
maybe we can move the file on completion

**Comment by cmod31** [comment]
completion?

**Comment by cmod31** [comment]
is it completed now i think so?

**Comment by xknat** [comment]
> is it completed now i think so?

yeah but maybe i will move the file from ./build/libs to ./

**Comment by AlexProgrammerDE** [comment]
Will close this one. You deleted your fork, which means I can't push an update commit for resolving the conflict. I'm gonna open a separate PR for this and push the needed stuff for merging it: https://github.com/SkinsRestorer/SkinsRestorerX/pull/668

**Pull request closed without merging**
