### PR TITLE
[Hotfix] v13.8.9 Remove no longer needed skintype check

### PR DESCRIPTION
**Pull request by xknat**
* bumb config to correct version

Co-authored-by: alexprogrammerde <alexprogrammerde@users.noreply.github.com>

### CODE REVIEW

**Comment by Logics4** [comment]
Can you not revert my commit? It literally fixes conflicts with other plugins. That's why I made that. Could you read the commit messages?

**Comment by xknat** [comment]
> Can you not revert my commit? It literally fixes conflicts with other plugins. That's why I made that. Could you read the commit messages?

Has this already been done in your last release v13.8.8?

if not, this should be the only hot fix and marking the end of v13.8.9 and target people to already move to v14.
v13.8.9 is absolute the moment its released because it's a announcement for v14 which is planned scheduled.

**Comment by Logics4** [comment]
No, it hadn't been done in 13.8.8 as the issue was only found after. It was something I planned for a future 13.8.9 (and I've mentioned that in our internal chat). The more bug fixes, the better. This pull request is not even about bStats.

**Comment by xknat** [comment]
> No, it hadn't been done in 13.8.8 as the issue was only found after. It was something I planned for a future 13.8.9 (and I've mentioned that in our internal chat). The more bug fixes, the better. This pull request is not even about bStats.

Understandable, but v14 already comes with a TON of more fixes, if they have issues. They should move to v14.
Can't have them stick to v13.8.9 just because its resolved there.

**Comment by Logics4** [comment]
They won't stick to 13.8.9 unless they want to. We won't offer them official support, anyway. The auto-updater will just do its job. We shouldn't be restoring bugs to serve as "future features", this is something I literally committed 28 days ago and it's been only brought up now.

**Comment by xknat** [comment]
> They won't stick to 13.8.9 unless they want to. We won't offer them official support, anyway. The auto-updater will just do its job. We shouldn't be restoring bugs to serve as "future features", this is something I literally committed 28 days ago and it's been only brought up now.

if i add it to the release, then i also want to add this and that and this feature and that improvement.
But that's not the whole point of the v13.8.9 release is just to point out to use v14

It's also untested... it would need to be tested possible delaying the release & release of v14 
I dont know what kind of errors it could give with other plugins etc.

**Comment by Logics4** [comment]
> if i add it to the release, then i also want to add this and that and this feature and that improvement.
It's literally a bug fix. It qualifies as a bug fix, the only type of commits we've been doing for the 13.x branch since we started working in v14.

> It's also untested... it would need to be tested possible delaying the release & release of v14
> I dont know what kind of errors it could give with other plugins etc.
 I tested it myself and it works. Literally the only two changes from bStats 1.x to bStats 2.x are:
- Now we also have to relocate bStats for Sponge (so just one thing in pom.xml);
- Sponge's bStats class has a different name.
We didn't have to change anything else in our side, coding-wise. It's been literally here for 28 days, 2.1.0 is not even the most recent version, v14 is already using 2.2.1. Aren't you still going to give a 13.8.9 jar for the testers to try?

**Comment by xknat** [comment]
> Aren't you still going to give a 13.8.9 jar for the testers to try?
no, thats the issue i want them to focus and test on v14
as v13.8.9 will MARK the end and the whole in BIG RED LETTERS in spigot release will be USE V14 NEW API!!

i want to minimalize changes and v2.2.1 has been tested but not 2.2.0
i dont want leave any chances / risk of this now breaking the whole plugin auto updater and everything we worked hard for.
i dont see adding the bstats update as a ESSENTIAL that MUST be added to v13.8.9 that could not wait *2 weeks* for v14 release
The only reason i am adding f1e48ef is to comply with spigot so that there is a purpose full change.

**Comment by Logics4** [comment]
Well, great then. Have you tested your skintype removal check commit for v13? Since it was originally made for v14, I think the potential bugs stemming from it could be worse than the bStats update if it's not totally compatible. I have tested my commit and it worked for its purpose.

If you want I can revert the changes for Bukkit and BungeeCord and keep only Sponge's, since it was the platform where the plugin conflicts were reported, and that the conflictuous plugins target.

**Comment by xknat** [comment]
81a0b19  is to be kept as a results on internal voting and will be merged into v13.8.9

**Pull request merged**
