### PR TITLE
Fix skin on resource packs

### LINKED ISSUE #582: Using SkinsRestorer on 1.17 breaks require-resourcepack feature
## Describe the bug
Installing and using SkinsRestorer on 1.17 breaks require-resourcepack feature somehow.

## How can we reproduce what you got?
1. Run latest Paper 1.17 build
2. Install SkinsRestorer
3. require-resourcepack=true in server.properties
4. Join the server, the window of confirmation won't appear and resourcepack won't be loaded

**Expected behavior**
Player joins the server, his skin will be set after pack is loaded.

**Screenshots**
Not available.

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Paper
* SkinsRestorer: 14.1.1
* Paper version: git-Paper-74
* Java: 16
* plugin list bungee & spigot: Only SkinsRestorer
* MinecraftLauncher?: Yes

### PR DESCRIPTION
**Pull request by OLEGSHA**
Fixes GH-582. **I haven't been able to test it.**

I fixed the issue by registering an always-present listener for `PlayerResourcePackStatusEvent`s. The listener may be disabled from config. Unless disabled, the listener executes a copy of the code of `SrCommand.onApplySkin()`.

### CODE REVIEW

**Comment by xknat** [comment]
Could be improved with Lombok.
Thanks anyways

**Comment by OLEGSHA** [comment]
> Could be improved with Lombok.

I'm not quite sure what you mean. I have never heard of Lombok before seeing a gazillion errors in my IDE when opening the project, so I wouldn't know how to use it properly. If you're planning on making stylistic changes to my contribution, please also check `SrCommand` and `PlayerJoin` since that's where I copied most of the code from.

P.S. I ended up writing the code in Kate instead of installing Lombok plugin like a normal person :)

**Review by xknat — APPROVED** [review]
LGTM, next step could be to read server.property in config.java to auto switch config.

**Comment by OLEGSHA** [comment]
Well, AFAIK `PlayerResourcePackStatusEvent` can only be generated if the client loads a resource pack on server's request, so why would it matter?

I'd rather be concerned that my commit effectively changes default behaviour. On one hand, it makes sense to enable the fix by default, but on the other hand, this might break existing setups, especially with automatic updates enabled.

**Comment by xknat** [comment]
Pr seems to be ready. I will give it out to our testers and test it my self

**Review by AlexProgrammerDE — CHANGES_REQUESTED** [review]
If I've seen this correctly, this would also require disabling onJoinSkins as well to work as expected. (It would still apply on join). I would suggest checking some way if a resource pack is getting applied on join somehow. Maybe by checking if there is a resource pack plugin or the server has a resource pack set? Also, the apply code should really be moved to an external method, so we get less code duplications.

**Comment by OLEGSHA** [comment]
I'll factor the common code out, it was bugging me as well.

I'm not sure there is a scenario when a `PlayerResourcePackStatusEvent` is generated when there is no server resourcepack. Why should we write a complex and unreliable piece of code that wouldn't change anything?

**Comment by xknat** [comment]
Think is that our plugin will cancel the resource pack prompt (with onjoinskin true).
So in this cause, the success will never hit since we force cancel it when onjoinskin.

So there should be some way to detect if a resource pack is being used (any resourcepack event to disable the onjoinskin)

**Comment by OLEGSHA** [comment]
> Think is that our plugin will cancel the resource pack prompt (with onjoinskin true).

Oh, right, I forgot about that. I'll do something about it then.

**Comment by xknat** [comment]
This should do.
Not that light weight...
but it does fix issues for sure.

If this dos slow down a lot of servers, we can maybe improve this.
functionality > performance > QOL

**Review by xknat — APPROVED** [review]
LGTM, maybe this can be improved in the future by not 2x applying the skin.

**Comment by xknat** [comment]
De Note: add a switch that when status.decline it will disable on join and make the resourcepack status one lead.

**Comment by xknat** [comment]
This should work on bukkit.
I don't know about bungee.

**Comment by xknat** [comment]
moved to https://github.com/SkinsRestorer/SkinsRestorerX/pull/916

**Pull request closed without merging**
