### PR TITLE
Delay updates

### PR DESCRIPTION
**Pull request by xknat**
Still some work is needed.
first appearance.

### CODE REVIEW

**Comment by xknat** [comment]
original updater seems to have been broken (as of latest commit), gotta look where i did broke it...

**Comment by xknat** [comment]
Seems to be that it does not want to download because of invalid url??
Think the url is send through class....

**Comment by Logics4** [comment]
Just a reminder for this new updater: as per the ["Update Checking" section of the Ore submission guidelines](https://docs.spongepowered.org/stable/en/ore/guidelines.html), we need to provide a way to fully disable the checker, at least for the Sponge part of our plugin:
```
Checking for updates should be performed using the provided Ore API. Your plugin may not link anywhere but Ore when directing users of your plugin to download new versions. Note that this update checking counts as an external connection, which must be documented and for which configuration must exist to disable it.
```

**Comment by xknat** [comment]
> Just as a reminder for this new updater: as per the ["Update Checking" section of the Ore submission guidelines](https://docs.spongepowered.org/stable/en/ore/guidelines.html), we need to provide a way to fully disable the checker, at least for the Sponge part of our plugin:
> 
> > Checking for updates should be performed using the provided Ore API. Your plugin may not link anywhere but Ore when directing users of your plugin to download new versions. Note that this update checking counts as an external connection, which must be documented and for which configuration must exist to disable it.

sponge version does not have an updater.

**Comment by Logics4** [comment]
Even though it does not force-update (like we are doing for Bukkit), it still does check if there is a new update. That's why I made that comment.

**Pull request closed without merging**
